### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by StevenTCramer** [chwebdude/DependencyChecker#1]
I go on VSTS and install your package as I want an automated way and visual indication if nuget packages are out of date.

But your instructions show some config screen that I don't know how to get to and you give no indication where I will see this report.  Nor how to start it?

Please update the documentation.

**Comment by chwebdude** [comment]
Hi Steven
Thank you for your interest. I added a simple "How to start" to the readme here https://github.com/chwebdude/DependencyChecker
Hope that helps a bit.
The important thing is, that you select the **Create Report** box. If you are using a standard build template, there is usually a "Publish Artifact" step at the end. This will copy the report to wherever its configured. By default this would be the artifact ZIP File of the build.

**Comment by StevenTCramer** [comment]
Ok so first of all.  From the market place.  One can't tell if this is a widget that sets on my dashboard or what.  With the mention of "Publish Artificat" I was able to deduce that oh maybe this extension is only used in part of the build process.  So I created a new build and search for the extension and there it is.

So update the docs to explain that this is "build task" extension.

I was hoping for a dashboard widget that showed you could configure which branch to look at and then show the report there.

**Comment by chwebdude** [comment]
Thank you for your feedback. I will enhance the documentation.
A dashboard widget would be cool, indeed, but at the moment I just don't have enough time for that...
