### ISSUE TITLE
Optimize Retrieval and Reporting

### ISSUE THREAD

**Issue by oicguy** [chwebdude/DependencyChecker#12]
I have a solution with 32 projects. While I get this isn't optimal, it is what it is and I can't do anything about that yet. DependencyChecker will go to each project, one at a time to determine the libraries used, then make calls to NuGet to receive the latest version info. For one or two projects this strategy is fine but it doesn't scale. All of the project share between 80% - 90% the same libraries, so why does the checker need to make a new call to NuGet for a package it has seen before?

Another way to handle this would be to gather all the packages from each project and filter the list to unique packages to obtain the packages for the whole solution, then just make all the nuget calls once. This would allow allow you to create a solution level report as well as the project level reports.

**Comment by chwebdude** [comment]
You are right. It doesn't scale well.
What do you think about an option like "Combine Projects" and this would generate a report of all packages. Then every package would be listed only once if it is everywhere in the same version.

**Comment by oicguy** [comment]
I am completely fine with that. While I currently don't have this happening, if a solution has two projects with the same package but they are on different versions, we'll still need a way to see that in the reports. This usually happens when one of my junior devs makes a new project but installs the packages from the 'Browse' tab instead of installing from the 'Install' tab using the current version installed in the solution.  So seeing that there are two version of the same package and seeing which project has the older version would be really handy, which is why I suggested keeping the original reports and adding the solution level report.

**Comment by chwebdude** [comment]
#14

**Comment by chwebdude** [comment]
Hi @oicguy 
I just released a new version with the wished option 😃 
Also the performance is optimized if a package is found multiple times. Hope it will help you to find error of your junio devs 😉

**Comment by oicguy** [comment]
That is completely awesome! I will try it out shortly. Thanks!

**Comment by chwebdude** [comment]
@oicguy  Could you try it out already? I have also added some support for Azure Artifacts #13 
If you are happy with the result don't forget to rate the extension on the Marketplace 😉
