### ISSUE TITLE
Artifact feed Uri support for legacy VSTS domains

### ISSUE THREAD

**Issue by kfoley100** [chwebdude/DependencyChecker#19]
Devops supports both new and legacy [Uri's ](https://docs.microsoft.com/en-us/azure/devops/extend/develop/work-with-urls?view=azure-devops&tabs=http):
https://{org}.visualstudio.com vs dev.azure.com/{org}

For those that haven't enabled the new Uri, pipelines will set SYSTEM_COLLECTIONURI to {org.visualstudio.com}, thus the injection of "pkgs." doesn't occur resulting in an invalid Uri.

Bad
https://{org}.visualstudio.com/_packaging/{guid}/nuget/v3/index.json
vs Good
https://{org}.pkgs.visualstudio.com/_packaging/{guid}/nuget/v3/index.json

buildtasks/index.ts : Line 58
// Add support for legacy Uri
artifactsUri = artifactsUri.replace("visualstudio.com", "pkgs.visualstudio.com");

**Comment by chwebdude** [comment]
https://github.com/chwebdude/DependencyChecker/commit/7004b64ff1131c586852b284ef8e4f8bd255e0cd

**Comment by chwebdude** [comment]
Hi @kfoley100 
Sorry for the long delay. I published an update. Could you please check if this works now for you?

**Comment by kfoley100** [comment]
Hello Fabrice,

Thanks for the code change, unfortunately I  cannot test this as we flipped
the switch on disabling the legacy URL so that we could use
DependencyChecker.

Thanks for a very useful piece of software.

Regards,

Kevin Foley
kfoley@quandis.com
949.525.9004
Quandis, Inc.
30021 Tomas, Suite 200
Rancho Santa Margarita, CA 92688
