### ISSUE TITLE
Add Project to the report output

### ISSUE THREAD

**Issue by JohannBlais** [chwebdude/DependencyChecker#2]
Hello,

Could you please add the project to the HTML report ?
We have a lot of projects in the solution, it is hard to know which project has outdated dependencies by just looking at the current output (most look like duplicated lines because of that).

Thank you !

**Comment by chwebdude** [comment]
Hi @JohannBlais 
Thank you first for your interest and sorry for the long delay...

Anyway: You're right. The output is not very nice when you are having a lot of projects. I created a new report format which groups the packages by project. Additionaly I added a simple Bootstrap styling so it also looks a bit nicer. Hope this will help you.
