### ISSUE TITLE
Add optional support for marking date based versions as outdated

### ISSUE THREAD

**Issue by ghost** [chwebdude/DependencyChecker#21]
Here's an example of internal dependencies that are outdated, but not labelled as such:

![image](https://user-images.githubusercontent.com/33350500/68326008-3ef8ba00-0090-11ea-87ac-d14c454ad5e5.png)

**Comment by fabricioferreira** [comment]
Please, check if this is still happening with the latest version (1.15.0). It has probably fixed it.
