### ISSUE TITLE
Devops Azure Feed not found

### ISSUE THREAD

**Issue by mpalese** [chwebdude/DependencyChecker#27]
If i select "Use Azure Artifacts" the job fails with this error: "Unhandled Exception: System.AggregateException: One or more errors occurred. ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source ...... ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found)."
I think the error is the url format:
Correct url
https://pkgs.dev.azure.com/{Organization}/{project}/_packaging/{feed}/nuget/v3/index.json
Bad url
https://pkgs.dev.azure.com/{Organization}/_packaging/{feed uid}/nuget/v3/index.json.

**Comment by fabricioferreira** [comment]
Can you check if this issue is still happening with the latest extension version?
