### ISSUE TITLE
Create report folder path if it does not exist

### ISSUE THREAD

**Issue by JohannBlais** [chwebdude/DependencyChecker#3]
Hello,

The task fails with an "invalid path error" if the output path for the HTML report does not exist.
I have to use a file copy task to move the HTML file and create the target folder.
It would be much easier if the extension would create the parent folder structure if necessary.

Thank you !

**Comment by chwebdude** [comment]
Thanks. This was a bug indeed. Now it calls the `Directory.CreateDirectory` method before creation.
