### ISSUE TITLE
Dependency status tab does not display results

### ISSUE THREAD

**Issue by robduncan-novia** [chwebdude/DependencyChecker#34]
I am able to generate the generate the dependency report as C:\a\2\a\dependencies.html but the dependency status tab still shows:
Data not ready yet. Please wait until the Dependency Check task has finished.

Is there something else I need to do to make it show?

My task is:
    - task: dependency-checker@1
      inputs:
          path: '$(Build.SourcesDirectory)'
          searchRecursive: true
          combineProjects: true
          includePrerelease: false
          useArtifacts: false
          createBadge: false
          createReport: true
          reportPath: '$(Build.ArtifactStagingDirectory)\dependencies.html'

**Comment by fabricioferreira** [comment]
Can you check if this issue is still happening with the latest extension version?
