### ISSUE TITLE
Task wrong check direction current version <=> installed version

### ISSUE THREAD

**Issue by BennyBread** [chwebdude/DependencyChecker#35]
Display & check in wrong direction?

The dependency report shows mostly  "Installed versions" higher then "Current Version" and status says "Up to date"

![image](https://user-images.githubusercontent.com/7902455/169048069-4922a06f-927e-428c-b54e-18f737c800cc.png)

I have installed the latest version from the Azure marketplace today..
What could be wrong here?
This is my YAML:

steps:
- task: chwebdude.dependency-checker.custom-build-task.dependency-checker@1
  displayName: 'Check nuget Dependencies'
  inputs:
    path: '$/Products/<SOMETHING>/Dev'
    combineProjects: true
    createBadge: true
    createReport: true

**Comment by fabricioferreira** [comment]
This issue has been fixed on version 1.15.0.
