### ISSUE TITLE
Is this project still maintained? Looking for contributors or a new owner?

### ISSUE THREAD

**Issue by fabricioferreira** [chwebdude/DependencyChecker#45]
I'm happy to take over this project if the author agrees.

**Comment by chwebdude** [comment]
Sorry, I don't have much time to maintain it at the moment. I invited you to the project so you can maintain the code. I will look into the build processes that they are going smooth.

**Comment by fabricioferreira** [comment]
Thank you! I will be glad to contribute to the project.
