### ISSUE TITLE
Build pipeline is copying executables to the wrong path

### ISSUE THREAD

**Issue by fabricioferreira** [chwebdude/DependencyChecker#50]
![image](https://user-images.githubusercontent.com/1106248/200187207-e810f109-0a0d-413c-98ac-7b2d39bb2cf5.png)

Check the image above: the executable files should be copied to the `bin/` folder, but are instead copied to `bin/net6.0/`. This causes the extension to fail when executed:

![image](https://user-images.githubusercontent.com/1106248/200187292-92ecbc32-35d8-49a5-83b2-1163d3c38d03.png)

**Comment by chwebdude** [comment]
The old build process had a bug. Hope it is fixed now and will switch to YAML build soon

**Comment by fabricioferreira** [comment]
Thanks, @chwebdude . This issue has been fixed.
