### ISSUE TITLE
Add support for PackageReference-using projects

### ISSUE THREAD

**Issue by frankshearar** [chwebdude/DependencyChecker#6]
VS 2017 introduces a new csproj format, which allows one to use <PackageReference> tags in the csproj instead of a separate packages.config file. It would be wonderful to see this new format supported.

**Comment by chwebdude** [comment]
This should be fixed the newest version 1.4.0. Please check and give feedback!

**Comment by Jorjo80** [comment]
I have use the Latest Version in master branch (the same that 1.12.0, they have no changes between Latest and 1.12.0 version LAbel) and it doesnt work.
