### ISSUE TITLE
Node Version EOL

### ISSUE THREAD

**Issue by mjones2003** [chwebdude/DependencyChecker#71]
Please can you update the node version referenced.  This is a great tool and I would love to see it continue.

##[warning]Task 'NuGet Dependency Check' version 1 (dependency-checker@1) is dependent on a Node version (6) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

**Comment by chwebdude** [comment]
Fixed with #75

**Comment by mjones2003** [comment]
> Fixed with #75

Thank you for maintaining this, we really like it
